#!/bin/sh

REMOTES=""
while read -r line; do
    if [ -z "$REMOTES" ]
    then
          REMOTES="${line}"
    else
          REMOTES="${REMOTES}\|${line}"
    fi
done < "${0%/hooks/*}/remotes"


remote_spec=$(git remote -v | grep "$(git remote)\s.*(push)$")

if [ -n "$(echo "${remote_spec}" | grep "$REMOTES")" ]
then
    expected_ref="DAT\|DAN"
    echo "Committing to vwt-digital repository, expect ${expected_ref} issue reference..."
fi

if [ -n "${expected_ref}" ]
then
	  grep "\(${expected_ref}\)-[0-9]\{3,\}" "$1"

    if [ $? -ne 0 ]
    then
        echo
        echo >&2 "ERROR: Missing required reference to issue, please add ${expected_ref}-nnn to your comment."
        echo >&2 "Your changes were not committed."
        exit 1
    else
      printf %s "✓ changes have been validated" >> "$1"
    fi
fi
